//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PPV_Projec_NEW_.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PPVdbEntities : DbContext
    {
        public PPVdbEntities()
            : base("name=PPVdbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Client> Clients { get; set; }
        public virtual DbSet<level> levels { get; set; }
        public virtual DbSet<MFG> MFGs { get; set; }
        public virtual DbSet<PN> PNs { get; set; }
        public virtual DbSet<PPV> PPVs { get; set; }
        public virtual DbSet<PPV_Fail> PPV_Fail { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<user> users { get; set; }
        public virtual DbSet<Vendor> Vendors { get; set; }
    }
}
